trigger:
- master

pr:
- master

pool:
  name: 'Default'   # your self-hosted agent pool

jobs:
- job: PlaywrightTests
  timeoutInMinutes: 60

  steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Set up Node.js'

  - script: npm ci
    displayName: 'Install dependencies'

  - script: npx playwright install --with-deps
    displayName: 'Install Playwright Browsers'

  
  - script: npm run test:sanity:chromium
  displayName: 'Run Playwright Tests (Chromium)'

  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      pathToPublish: 'playwright-report'
      artifactName: 'playwright-report'
      publishLocation: 'Container'
