trigger:
- master

pr:
- master

pool:
  name: 'Default'

jobs:
- job: PlaywrightTests
  timeoutInMinutes: 60

  steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Set up Node.js'

  - script: npm ci
    displayName: 'Install dependencies'

  - script: npx playwright install chromium
    displayName: 'Install Chromium only'

  - script: npm run test:sanity:chromium
    displayName: 'Run Playwright Tests (Chromium)'

  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      pathToPublish: 'playwright-report'
      artifactName: 'playwright-report'
      publishLocation: 'Container'

  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/results.xml'

  - task: Cache@2
    inputs:
      key: 'npm | "$(Agent.OS)" | package-lock.json'
      path: 'node_modules'
      restoreKeys: |
        npm | "$(Agent.OS)"
